server:
  Addr: 0.0.0.0
  Port: 8008

user_db:
  DriverName: mysql
  Database: crud-list
  Port: 3306
  UserName: root
  Password: 123456
  Host: 127.0.0.1 #host.docker.internal #
  Charset: utf8mb4

user_redis:
  Addr: "localhost:6379"
  Password: "123456"


# token 签发配置
token:
  shortDuration: 30   # token 有效期（分钟），多久无操作就退出
  longDuration: 1440  # 长 token，多久必须重新登陆

etcd:
  Endpoint: "127.0.0.1:2379"
  keys:
    crud_rpc: crud_rpc
