server:
  Name: curd_rpc
  Listen: "0.0.0.0:8080"
  Addr: "127.0.0.1:8080"

db:
  DriverName: mysql
  Database: crud-list
  Port: 3306
  UserName: root
  Password: 123456
  Host: 127.0.0.1 #host.docker.internal #
  Charset: utf8mb4

etcd:
  Endpoint: "127.0.0.1:2379"